import type { Lang } from "./types";

const stages = {
  en: [
    { name: "Case the target", line: "Someone you do not know is claiming to be an official." },
    { name: "Build the con", line: "Real agencies do not threaten arrest by text or phone." },
    { name: "Urgency and isolation", line: "You are being rushed and told to keep it secret. That is how scams work." },
    { name: "The getaway", line: "This payment cannot be undone. Let us check with someone you trust first." },
  ],
  es: [
    { name: "Estudian el blanco", line: "Alguien que usted no conoce dice ser un funcionario." },
    { name: "Arman el cuento", line: "Las oficinas de verdad no amenazan con arresto por texto o por teléfono." },
    { name: "Prisa y secreto", line: "Le están apurando y le piden secreto. Así funcionan las estafas." },
    { name: "La huida", line: "Este pago no se puede deshacer. Primero preguntémosle a alguien de su confianza." },
  ],
} as const;

export const copy = {
  en: {
    brand: "Scam Shield",
    chrome: "Vault · Crew · Getaway · Alarm",
    banner: "Practice wallet. No real money moves.",
    setupTitle: "Who should the alarm call?",
    setupBody: "Pick one person you trust. They can approve a payment only when the alarm goes off. You chose them, and you can change them.",
    startRosa: "Start as Rosa",
    rosaNote: "Rosa's trusted person is Maya. This is the practice pair.",
    yourName: "Your name",
    yourPhone: "Your phone",
    theirName: "Person you trust",
    theirPhone: "Their phone",
    create: "Create the alarm",
    english: "English",
    spanish: "Español",
    linkTitle: "Open this on their phone",
    linkBody: "They should keep this page open. It updates when a payment is held.",
    enterWallet: "Go to the wallet",
    sendTitle: "Send money",
    amount: "Amount",
    recipient: "Who is this for?",
    method: "How will it send?",
    prompt: "What made you send this?",
    promptHint: "Paste the text, add a photo, or say it out loud.",
    irs: "Use the IRS text",
    normal: "Use a normal bill",
    photo: "Add a photo",
    voice: "Say it aloud",
    checkMessage: "Check a message first",
    primary: "Check before sending",
    methods: {
      ach: "Bank transfer",
      instant: "Instant transfer",
      wire: "Wire",
      gift_card: "Gift card",
      crypto: "Crypto",
    },
    checking: "Checking the vault",
    heistTitle: "Heist in progress",
    hear: "Hear the warning",
    ask: (name: string) => `Ask ${name}`,
    cancel: "Cancel payment",
    verifyTitle: "Pause and look",
    q1: "Are you on the phone with the person who asked for this money?",
    q2: "Did they tell you not to tell anyone?",
    yes: "Yes",
    no: "No",
    continuePay: "Continue payment",
    waitingTitle: "Waiting for the crew",
    waitingBody: (name: string) => `${name} has the alarm. The payment stays here until they answer. You can still cancel.`,
    fact: "Fact",
    userReport: "What they said",
    inference: "What the alarm noticed",
    unknown: "What we cannot know",
    action: "What you can do",
    approve: "Approve",
    deny: "Deny",
    call: (name: string) => `Call ${name}`,
    allowedTitle: "This payment can proceed",
    allowedBody: "Nothing about it matched a scam pattern. This practice wallet still does not move money.",
    approvedTitle: "Your person said yes",
    approvedBody: "They released the hold. A real bank could send it now. This practice wallet does not move money.",
    deniedTitle: "Your person said no",
    deniedBody: "Hang up if someone is on the line. Call the company using the number on its official website, not the number in the message.",
    expiredTitle: "They have not answered",
    expiredBody: (name: string) => `The payment stays held. Call ${name} another way, or report the message.`,
    cancelledTitle: "Payment cancelled",
    cancelledBody: "No money moves. You can start again.",
    another: "Start another payment",
    report: "How to report it",
    ftc: "Report to the FTC",
    fbi: "Report to the FBI",
    local: "San Antonio phone numbers are left off until someone confirms them.",
    history: "Past attempts",
    noAlarm: "No alarm right now",
    noAlarmBody: (name: string) => `When ${name} hits a hold, this phone shows the facts and two choices.`,
    messageTitle: "Check a message",
    messageBody: "See how far the story has gone before any money moves.",
    seeStage: "See the stage",
    back: "Back to the wallet",
    backAlarm: "Back to the alarm",
    stageNone: "No heist signals in this message.",
    score: "Risk",
    of: "of 100",
    readBy: {
      gemini: "Read by Gemini",
      fallback: "Offline rules, no Gemini key",
      none: "No message to read",
    },
    stages: stages.en,
    error: "The alarm could not reach the vault. Check the connection and try again.",
    pressureTitle: "Pressure check",
    pressureBody: "The camera can read pulse and breathing. A jump adds 10 points after a 15 second baseline. This is a wellness signal, not a medical reading.",
    pressureWaiting: "Waiting for Presage samples. The score does not change until a real reading arrives.",
    pressureReady: "Baseline ready.",
    pressureHigh: "Pulse or breathing is elevated. The next payment check can add 10 points.",
    copyLink: "Copy link",
    copied: "Copied",
    chartTitle: "Attempts and holds",
    tigerOn: "Live from Tiger Data",
    tigerOff: "Chart is ready. It uses Tiger Data when that database is connected.",
    photoAdded: "Photo added",
    listening: "Listening…",
  },
  es: {
    brand: "Scam Shield",
    chrome: "Bóveda · Equipo · Huida · Alarma",
    banner: "Billetera de práctica. No se mueve dinero de verdad.",
    setupTitle: "¿A quién debe llamar la alarma?",
    setupBody: "Elija a una persona de su confianza. Esa persona puede aprobar un pago solo cuando suena la alarma. Usted la eligió y puede cambiarla.",
    startRosa: "Empezar como Rosa",
    rosaNote: "La persona de confianza de Rosa es Maya. Esta es la pareja de práctica.",
    yourName: "Su nombre",
    yourPhone: "Su teléfono",
    theirName: "Persona de confianza",
    theirPhone: "Su teléfono",
    create: "Crear la alarma",
    english: "English",
    spanish: "Español",
    linkTitle: "Abra esto en su teléfono",
    linkBody: "Esa persona debe dejar esta página abierta. Se actualiza cuando un pago queda detenido.",
    enterWallet: "Ir a la billetera",
    sendTitle: "Enviar dinero",
    amount: "Cantidad",
    recipient: "¿Para quién es?",
    method: "¿Cómo se envía?",
    prompt: "¿Qué le hizo enviar esto?",
    promptHint: "Pegue el texto, agregue una foto, o dígalo en voz alta.",
    irs: "Usar el texto del IRS",
    normal: "Usar una factura normal",
    photo: "Agregar una foto",
    voice: "Decirlo en voz alta",
    checkMessage: "Revisar un mensaje primero",
    primary: "Revisar antes de enviar",
    methods: {
      ach: "Transferencia bancaria",
      instant: "Transferencia instantánea",
      wire: "Giro",
      gift_card: "Tarjeta de regalo",
      crypto: "Cripto",
    },
    checking: "Revisando la bóveda",
    heistTitle: "Atraco en curso",
    hear: "Escuchar el aviso",
    ask: (name: string) => `Pregúntale a ${name}`,
    cancel: "Cancelar el pago",
    verifyTitle: "Pausa y mire",
    q1: "¿Está usted al teléfono con la persona que pidió este dinero?",
    q2: "¿Le dijeron que no se lo contara a nadie?",
    yes: "Sí",
    no: "No",
    continuePay: "Seguir con el pago",
    waitingTitle: "Esperando al equipo",
    waitingBody: (name: string) => `${name} tiene la alarma. El pago se queda aquí hasta que conteste. Usted todavía puede cancelar.`,
    fact: "Hecho",
    userReport: "Lo que dijo",
    inference: "Lo que notó la alarma",
    unknown: "Lo que no podemos saber",
    action: "Lo que usted puede hacer",
    approve: "Aprobar",
    deny: "Rechazar",
    call: (name: string) => `Llamar a ${name}`,
    allowedTitle: "Este pago puede seguir",
    allowedBody: "Nada coincidió con un patrón de estafa. Esta billetera de práctica no mueve dinero.",
    approvedTitle: "Su persona dijo que sí",
    approvedBody: "Soltó la pausa. Un banco de verdad podría enviarlo ahora. Esta billetera de práctica no mueve dinero.",
    deniedTitle: "Su persona dijo que no",
    deniedBody: "Cuelgue si alguien está en la línea. Llame a la oficina con el número de su sitio oficial, no con el número del mensaje.",
    expiredTitle: "No han contestado",
    expiredBody: (name: string) => `El pago sigue detenido. Llame a ${name} de otra forma, o reporte el mensaje.`,
    cancelledTitle: "Pago cancelado",
    cancelledBody: "No se mueve dinero. Puede empezar de nuevo.",
    another: "Empezar otro pago",
    report: "Cómo reportarlo",
    ftc: "Reportar a la FTC",
    fbi: "Reportar al FBI",
    local: "Los teléfonos de San Antonio quedan fuera hasta que alguien los confirme.",
    history: "Intentos anteriores",
    noAlarm: "No hay alarma ahora",
    noAlarmBody: (name: string) => `Cuando ${name} tenga un pago detenido, este teléfono muestra los hechos y dos opciones.`,
    messageTitle: "Revisar un mensaje",
    messageBody: "Vea hasta dónde llegó la historia antes de que se mueva el dinero.",
    seeStage: "Ver la etapa",
    back: "Volver a la billetera",
    backAlarm: "Volver a la alarma",
    stageNone: "Este mensaje no tiene señales de atraco.",
    score: "Riesgo",
    of: "de 100",
    readBy: {
      gemini: "Leído por Gemini",
      fallback: "Reglas sin conexión, sin llave de Gemini",
      none: "No hay mensaje para leer",
    },
    stages: stages.es,
    error: "La alarma no pudo llegar a la bóveda. Revise la conexión e intente de nuevo.",
    pressureTitle: "Control de presión",
    pressureBody: "La cámara puede leer el pulso y la respiración. Un salto suma 10 puntos después de una base de 15 segundos. Es una señal de bienestar, no una lectura médica.",
    pressureWaiting: "Esperando muestras de Presage. La puntuación no cambia hasta que llega una lectura real.",
    pressureReady: "Base lista.",
    pressureHigh: "El pulso o la respiración está elevado. La próxima revisión puede sumar 10 puntos.",
    copyLink: "Copiar enlace",
    copied: "Copiado",
    chartTitle: "Intentos y pausas",
    tigerOn: "En vivo desde Tiger Data",
    tigerOff: "La gráfica está lista. Usa Tiger Data cuando esa base está conectada.",
    photoAdded: "Foto agregada",
    listening: "Escuchando…",
  },
} as const;

export function text(language: Lang) {
  return copy[language];
}
