import type { Lang } from "./types";

const stages = {
  en: [
    { who: "The Caser", name: "Cases the target", line: "Someone you do not know is claiming to be an official." },
    { who: "The Talker", name: "Builds the con", line: "Real agencies do not threaten arrest by text or phone." },
    { who: "The Clock", name: "Rushes and isolates", line: "You are being rushed and told to keep it secret. That is how scams work." },
    { who: "The Wheelman", name: "Drives the getaway", line: "This payment cannot be undone. Let us check with someone you trust first." },
  ],
  es: [
    { who: "El Observador", name: "Estudia el blanco", line: "Alguien que usted no conoce dice ser un funcionario." },
    { who: "El Cuentista", name: "Arma el cuento", line: "Las oficinas de verdad no amenazan con arresto por texto o por teléfono." },
    { who: "El Reloj", name: "Apura y aísla", line: "Le están apurando y le piden secreto. Así funcionan las estafas." },
    { who: "El Conductor", name: "Lleva la huida", line: "Este pago no se puede deshacer. Primero preguntémosle a alguien de su confianza." },
  ],
} as const;

export const copy = {
  en: {
    brand: "Lookout",
    landLead: "A risky payment waits until someone you trust agrees.",
    landNote: "On a computer, the wallet sits in one phone. On your own phone, it fills the screen.",
    openWallet: "Open the wallet",
    openLookout: "Open Maya's phone",
    chrome: "Scam shield · active",
    banner: "Practice wallet. No real money moves.",
    shield: "Scam shield",
    shieldNote: "Watching this payment for you",
    showDetails: "Show the checks behind this",
    hideDetails: "Hide the checks",
    agentCallBtn: "Have the agent call my phone",
    agentCallHint: "We'll ring your phone and talk it through together.",
    yourNumber: "Your phone number",
    callPlace: "Call me now",
    callingNow: "Your phone is ringing. Pick up and talk it through.",
    callSetup: "Connect a Twilio number to turn this on.",
    callFailed: "Could not place the call.",
    roles: {
      keeper: "You are the Keeper",
      lookout: "You are the Lookout",
      alarm: "The Alarm is ringing",
      dial: "The Dial is turning",
      ledger: "The Ledger",
      pulse: "The Pulse",
    },
    setupTitle: "You are the Keeper.",
    setupBody: "Name your Lookout. They can approve a payment only when the Alarm goes off. You chose them, and you can change them.",
    castNote: "Four faces run the job: the Caser, the Talker, the Clock, and the Wheelman. The Alarm names which face is in the room.",
    startRosa: "Play as Rosa",
    rosaNote: "Rosa is the Keeper. Maya is the Lookout. This is the practice crew.",
    yourName: "Your name",
    yourPhone: "Your phone",
    theirName: "Person you trust",
    theirPhone: "Their phone",
    create: "Create the alarm",
    english: "English",
    spanish: "Español",
    linkTitle: "Hand this to your Lookout",
    linkBody: "They keep this page open. It lights when a payment is held.",
    enterWallet: "Go to the wallet",
    sendTitle: "Send money",
    amount: "Amount",
    recipient: "Who is this for?",
    method: "How will it send?",
    prompt: "What made you send this?",
    promptHint: "Paste the text, add a photo, or say it out loud.",
    whyTitle: "Why are you transferring this amount?",
    whyHint: "Ranked by threat. A denial raises a reason. A finished payment lowers it. One reason cannot hold the payment by itself.",
    threat: { high: "High threat", mid: "Medium threat", low: "Low threat" },
    whyHeat: (points: number) => (points > 0 ? `Adds ${points} heat` : "Does not add heat"),
    whyChosen: (label: string, rank: number, total: number, level: string) =>
      `You said: ${label} Threat rank ${rank} of ${total}, ${level}.`,
    whyLearned: (disputes: number, successes: number) =>
      `Learned from ${disputes} ${disputes === 1 ? "dispute" : "disputes"} and ${successes} finished ${successes === 1 ? "payment" : "payments"}.`,
    irs: "Use the IRS text",
    normal: "Use a normal bill",
    photo: "Add a photo",
    voice: "Say it aloud",
    checkMessage: "Review a call or message",
    primary: "Check before sending",
    methods: {
      ach: "Bank transfer",
      instant: "Instant transfer",
      wire: "Wire",
      gift_card: "Gift card",
      crypto: "Crypto",
    },
    checking: "The Dial is turning",
    heistTitle: "Heist in progress",
    hear: "Hear the warning",
    ask: (name: string) => `Ask ${name}`,
    cancel: "Cancel payment",
    verifyTitle: "Pause and look",
    q1: "Are you on the phone with the person who asked for this money?",
    q2: "Did they tell you not to tell anyone?",
    yes: "Yes",
    no: "No",
    continuePay: "Continue payment",
    waitingTitle: "Waiting on the Lookout",
    waitingBody: (name: string) => `${name} has the radio. The payment stays in the vault until they answer. You can still cancel.`,
    fact: "Fact",
    userReport: "What they said",
    inference: "What the alarm noticed",
    unknown: "What we cannot know",
    action: "What you can do",
    approve: "Approve",
    deny: "Deny",
    call: (name: string) => `Call ${name}`,
    allowedTitle: "The vault is clear",
    allowedBody: "Nothing about it matched a scam pattern. This practice wallet still does not move money.",
    approvedTitle: "Your person said yes",
    approvedBody: "They released the hold. A real bank could send it now. This practice wallet does not move money.",
    deniedTitle: "Your person said no",
    deniedBody: "Hang up if someone is on the line. Call the company using the number on its official website, not the number in the message.",
    expiredTitle: "They have not answered",
    expiredBody: (name: string) => `The payment stays held. Call ${name} another way, or report the message.`,
    cancelledTitle: "Payment cancelled",
    cancelledBody: "No money moves. You can start again.",
    another: "Start another payment",
    report: "How to report it",
    ftc: "Report to the FTC",
    fbi: "Report to the FBI",
    local: "San Antonio phone numbers are left off until someone confirms them.",
    history: "The Ledger",
    noAlarm: "The Lookout is quiet",
    noAlarmBody: (name: string) => `When ${name}, the Keeper, hits a hold, this phone names the face and gives you two choices.`,
    messageTitle: "Review what they said",
    messageBody: "Paste the text, or say what you heard on the call. The reviewer reads only those words. It does not join the call or record the line.",
    seeStage: "Review it",
    doctorSample: "Use the doctor call",
    useReason: "Use this answer on the payment",
    looked: "Who looked",
    addWatcher: "Add a watcher",
    addWatcherHint: "A watcher notices words you choose and may add one pattern. One pattern cannot hold a payment.",
    watcherName: "Name",
    watcherWords: "Words, separated by commas",
    watcherPattern: "Pattern it may add",
    patterns: {
      urgency: "They are rushing",
      secrecy: "They want it secret",
      authority_claim: "They claim to be an official",
      threat_or_reward: "They are threatening",
      sensitive_request: "They want a code, a gift card, or a new account",
    },
    back: "Back to the wallet",
    backAlarm: "Back to the alarm",
    stageNone: "No heist signals in this message.",
    score: "Heat",
    of: "of 100",
    readBy: {
      gemini: "Read by Gemini",
      fallback: "Offline rules, no Gemini key",
      none: "No message to read",
    },
    stages: stages.en,
    error: "The alarm could not reach the vault. Check the connection and try again.",
    pressureTitle: "The Pulse",
    pressureBody: "The camera can read pulse and breathing. A jump adds 10 points of heat after a 15 second baseline. This is a wellness signal, not a medical reading.",
    pressureWaiting: "Waiting for Presage samples. The score does not change until a real reading arrives.",
    pressureReady: "Baseline ready.",
    pressureHigh: "Pulse or breathing is elevated. The next payment check can add 10 points.",
    copyLink: "Copy link",
    copied: "Copied",
    chartTitle: "Attempts and holds",
    tigerOn: "Live from Tiger Data",
    tigerOff: "Chart is ready. It uses Tiger Data when that database is connected.",
    photoAdded: "Photo added",
    listening: "Listening…",
  },
  es: {
    brand: "Lookout",
    landLead: "Un pago riesgoso espera hasta que alguien de su confianza esté de acuerdo.",
    landNote: "En una computadora, la billetera cabe en un teléfono. En su propio teléfono, llena la pantalla.",
    openWallet: "Abrir la billetera",
    openLookout: "Abrir el teléfono de Maya",
    chrome: "Escudo antiestafa · activo",
    banner: "Billetera de práctica. No se mueve dinero de verdad.",
    shield: "Escudo antiestafa",
    shieldNote: "Cuidando este pago por usted",
    showDetails: "Ver las comprobaciones",
    hideDetails: "Ocultar las comprobaciones",
    agentCallBtn: "Que el agente me llame",
    agentCallHint: "Llamamos a su teléfono y lo hablamos juntos.",
    yourNumber: "Su número de teléfono",
    callPlace: "Llámeme ahora",
    callingNow: "Su teléfono está sonando. Conteste y hablémoslo.",
    callSetup: "Conecte un número de Twilio para activar esto.",
    callFailed: "No se pudo hacer la llamada.",
    roles: {
      keeper: "Usted es el Guardián",
      lookout: "Usted es el Vigía",
      alarm: "La Alarma está sonando",
      dial: "El Cerrojo está girando",
      ledger: "El Libro",
      pulse: "El Pulso",
    },
    setupTitle: "Usted es el Guardián.",
    setupBody: "Nombre a su Vigía. Esa persona puede aprobar un pago solo cuando suena la Alarma. Usted la eligió y puede cambiarla.",
    castNote: "Cuatro caras hacen el trabajo: el Observador, el Cuentista, el Reloj y el Conductor. La Alarma dice cuál está en la sala.",
    startRosa: "Jugar como Rosa",
    rosaNote: "Rosa es el Guardián. Maya es el Vigía. Esta es la pareja de práctica.",
    yourName: "Su nombre",
    yourPhone: "Su teléfono",
    theirName: "Persona de confianza",
    theirPhone: "Su teléfono",
    create: "Crear la alarma",
    english: "English",
    spanish: "Español",
    linkTitle: "Entregue esto a su Vigía",
    linkBody: "Esa persona deja esta página abierta. Se enciende cuando un pago queda detenido.",
    enterWallet: "Ir a la billetera",
    sendTitle: "Enviar dinero",
    amount: "Cantidad",
    recipient: "¿Para quién es?",
    method: "¿Cómo se envía?",
    prompt: "¿Qué le hizo enviar esto?",
    promptHint: "Pegue el texto, agregue una foto, o dígalo en voz alta.",
    whyTitle: "¿Por qué está transfiriendo esta cantidad?",
    whyHint: "Ordenadas por amenaza. Un rechazo sube una razón. Un pago terminado la baja. Una sola razón no puede detener el pago.",
    threat: { high: "Amenaza alta", mid: "Amenaza media", low: "Amenaza baja" },
    whyHeat: (points: number) => (points > 0 ? `Suma ${points} de calor` : "No suma calor"),
    whyChosen: (label: string, rank: number, total: number, level: string) =>
      `Usted dijo: ${label} Puesto ${rank} de ${total}, ${level}.`,
    whyLearned: (disputes: number, successes: number) =>
      `Aprendido de ${disputes} ${disputes === 1 ? "rechazo" : "rechazos"} y ${successes} ${successes === 1 ? "pago terminado" : "pagos terminados"}.`,
    irs: "Usar el texto del IRS",
    normal: "Usar una factura normal",
    photo: "Agregar una foto",
    voice: "Decirlo en voz alta",
    checkMessage: "Revisar una llamada o un mensaje",
    primary: "Revisar antes de enviar",
    methods: {
      ach: "Transferencia bancaria",
      instant: "Transferencia instantánea",
      wire: "Giro",
      gift_card: "Tarjeta de regalo",
      crypto: "Cripto",
    },
    checking: "El Cerrojo está girando",
    heistTitle: "Atraco en curso",
    hear: "Escuchar el aviso",
    ask: (name: string) => `Pregúntale a ${name}`,
    cancel: "Cancelar el pago",
    verifyTitle: "Pausa y mire",
    q1: "¿Está usted al teléfono con la persona que pidió este dinero?",
    q2: "¿Le dijeron que no se lo contara a nadie?",
    yes: "Sí",
    no: "No",
    continuePay: "Seguir con el pago",
    waitingTitle: "Esperando al Vigía",
    waitingBody: (name: string) => `${name} tiene el radio. El pago se queda en la bóveda hasta que conteste. Usted todavía puede cancelar.`,
    fact: "Hecho",
    userReport: "Lo que dijo",
    inference: "Lo que notó la alarma",
    unknown: "Lo que no podemos saber",
    action: "Lo que usted puede hacer",
    approve: "Aprobar",
    deny: "Rechazar",
    call: (name: string) => `Llamar a ${name}`,
    allowedTitle: "La bóveda está despejada",
    allowedBody: "Nada coincidió con un patrón de estafa. Esta billetera de práctica no mueve dinero.",
    approvedTitle: "Su persona dijo que sí",
    approvedBody: "Soltó la pausa. Un banco de verdad podría enviarlo ahora. Esta billetera de práctica no mueve dinero.",
    deniedTitle: "Su persona dijo que no",
    deniedBody: "Cuelgue si alguien está en la línea. Llame a la oficina con el número de su sitio oficial, no con el número del mensaje.",
    expiredTitle: "No han contestado",
    expiredBody: (name: string) => `El pago sigue detenido. Llame a ${name} de otra forma, o reporte el mensaje.`,
    cancelledTitle: "Pago cancelado",
    cancelledBody: "No se mueve dinero. Puede empezar de nuevo.",
    another: "Empezar otro pago",
    report: "Cómo reportarlo",
    ftc: "Reportar a la FTC",
    fbi: "Reportar al FBI",
    local: "Los teléfonos de San Antonio quedan fuera hasta que alguien los confirme.",
    history: "El Libro",
    noAlarm: "El Vigía está en calma",
    noAlarmBody: (name: string) => `Cuando ${name}, el Guardián, tenga un pago detenido, este teléfono nombra la cara y le da dos opciones.`,
    messageTitle: "Revise lo que dijeron",
    messageBody: "Pegue el texto, o diga lo que escuchó en la llamada. El revisor lee solo esas palabras. No entra a la llamada ni graba la línea.",
    seeStage: "Revisarlo",
    doctorSample: "Usar la llamada del médico",
    useReason: "Usar esta respuesta en el pago",
    looked: "Quién miró",
    addWatcher: "Agregar un vigilante",
    addWatcherHint: "Un vigilante nota las palabras que usted elige y puede sumar un patrón. Un patrón no puede detener un pago.",
    watcherName: "Nombre",
    watcherWords: "Palabras, separadas por comas",
    watcherPattern: "Patrón que puede sumar",
    patterns: {
      urgency: "Le están apurando",
      secrecy: "Quieren secreto",
      authority_claim: "Dicen ser un funcionario",
      threat_or_reward: "Están amenazando",
      sensitive_request: "Quieren un código, una tarjeta de regalo o una cuenta nueva",
    },
    back: "Volver a la billetera",
    backAlarm: "Volver a la alarma",
    stageNone: "Este mensaje no tiene señales de atraco.",
    score: "Calor",
    of: "de 100",
    readBy: {
      gemini: "Leído por Gemini",
      fallback: "Reglas sin conexión, sin llave de Gemini",
      none: "No hay mensaje para leer",
    },
    stages: stages.es,
    error: "La alarma no pudo llegar a la bóveda. Revise la conexión e intente de nuevo.",
    pressureTitle: "El Pulso",
    pressureBody: "La cámara puede leer el pulso y la respiración. Un salto suma 10 puntos de calor después de una base de 15 segundos. Es una señal de bienestar, no una lectura médica.",
    pressureWaiting: "Esperando muestras de Presage. La puntuación no cambia hasta que llega una lectura real.",
    pressureReady: "Base lista.",
    pressureHigh: "El pulso o la respiración está elevado. La próxima revisión puede sumar 10 puntos.",
    copyLink: "Copiar enlace",
    copied: "Copiado",
    chartTitle: "Intentos y pausas",
    tigerOn: "En vivo desde Tiger Data",
    tigerOff: "La gráfica está lista. Usa Tiger Data cuando esa base está conectada.",
    photoAdded: "Foto agregada",
    listening: "Escuchando…",
  },
} as const;

export function text(language: Lang) {
  return copy[language];
}
